- hosts: flaskapp_nodes
  become: yes
  vars: 
    APP_REPO: "https://github.com/pwoicik/CeneoScraper.git"
    APP_NAME: "scraper"

  tasks:
    - name: "Install git and pip3"
      yum:
        name: git, python3-pip
        state: present

    - name: "Pull git repo"
      git:
        repo: "{{ APP_REPO }}"
        dest: "/opt/{{ APP_NAME }}"

    - name: "Create a new user"
      user: 
        name: "{{ APP_NAME }}"

    - name: "Change app's working directory permissions"
      file:
        owner: "{{APP_NAME}}"
        group: "{{APP_NAME}}"
        path: "/opt/{{APP_NAME}}"
        recurse: yes

    - name: "Create venv and install dependencies"
      pip:
        requirements: "/opt/{{ APP_NAME }}/requirements.txt"
        virtualenv: "/opt/{{ APP_NAME }}/.venv"
        virtualenv_command: python3 -m venv

    - name: "Create flask app service"
      template:
        src: files/app.service
        dest: "/etc/systemd/system/{{ APP_NAME }}.service"

    - name: "Start flask app service"
      systemd:
        daemon_reload: yes
        name: "{{ APP_NAME }}"
        state: restarted

- hosts: proxy_nodes
  become: yes
  vars:
    app_ips:
      - 172.31.6.98:8080

  tasks:
    - name: "Install EPEL"
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: "Install nginx"
      yum:
        name: nginx
        state: present

    - name: "Put nginx config"
      template:
        src: files/proxy.conf
        dest: /etc/nginx/conf.d/blog.conf

    - name: "Reload nginx"
      systemd:
        name: nginx
        state: reloaded
